name: PR Workflow with Acceptance Testing

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  approval:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: acceptance_testing
    steps:
      - name: Await Acceptance Testing
        run: echo "Deployment will pause here until manually approved via the environment settings."

      - name: Acceptance Testing Passed
        run: echo "Deployment steps proceed after the environment is approved."
