name: Auto Create PR from Staging to Main

on:
  push:
    branches:
      - staging

permissions:
  pull-requests: write
  contents: read

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check for existing PR and merge status, then create PR if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node --input-type=module -e "
          import { execSync } from 'child_process';

          try {
            // Check if there is already an open PR from staging to main
            const listCommand = 'gh pr list --head staging --base main --state open --json number --jq \". | length\"';
            const prCount = parseInt(execSync(listCommand, { encoding: 'utf8' }).trim(), 10);

            // Ensure we have the latest main branch
            execSync('git fetch origin main');

            // Check if staging is merged into main
            let stagingMerged = false;
            try {
              execSync('git merge-base --is-ancestor staging origin/main');
              stagingMerged = true;
            } catch (e) {
              stagingMerged = false;
            }

            if (prCount > 0) {
              console.log('An open PR from staging to main already exists. Skipping creation.');
              process.exit(0);
            }
            if (stagingMerged) {
              console.log('Staging branch is already merged into main. Skipping PR creation.');
              process.exit(0);
            }

            // Create a new PR if neither condition applies.
            const createCommand = \`gh pr create --title "Auto PR: Merge staging into main" --body "This PR was automatically created from a commit to the staging branch." --base main --head staging\`;
            console.log('Executing command:', createCommand);
            execSync(createCommand, { stdio: 'inherit' });
            console.log('PR created successfully.');
          } catch (error) {
            console.error('Error creating PR:', error);
            process.exit(1);
          }
          "
