name: Deployment - Demo

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Step 1
      run: echo "Running step 1"

    - name: Step 2
      run: echo "Running step 2"

    - name: Step 3
      run: echo "Running step 3"

    - name: Step 4
      run: echo "Running step 4"

    - name: Deploy to Demo
      run: echo "Deploying to demo environment"
