name: Demo Workflow

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: demo

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Step 1
      run: echo "Running step 1"

    - name: Step 2
      run: echo "Running step 2"

    - name: Step 3
      run: echo "Running step 3"

    - name: Step 4
      run: echo "Running step 4"

    - name: Deploy to Demo
      run: echo "Deploying to demo environment"
      
  create-pull-request:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}  # Ensuring the workflow runs on the commit that triggered it

      - name: Get Commit Message
        id: get_commit_message
        run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-create PR from staging to main"
          branch: staging
          base: main
          title: "Auto PR: Merge staging into main - ${{ env.commit_message }}"
          body: "This PR is automatically created to merge changes from staging into main.\n\nOriginal commit message:\n\n${{ env.commit_message }}"
          labels: "auto-created"
