name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Step 1
      run: echo "Running step 1"

    - name: Step 2
      run: echo "Running step 2"

    - name: Step 3
      run: echo "Running step 3"

    - name: Step 4
      run: echo "Running step 4"

  # 2) Only if build succeeds, require manual approval through an environment
  manual_approval:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
    steps:
      - name: Prepare for Deployment
        run: echo "All checks passed. Once production environment is approved, continue."

      - name: Deploy
        run: echo "Deployment commands go here, executed after manual approval."
